univers_catalog:
  PocketFlowCore:
    modules:
      - Flow
      - Node
      - Transition
      - SharedStore
  StructureAgentIA:
    modules:
      - ManagerGoal
      - ManagerTask
      - MCPNode
      - InputParserNode
  KnowledgeLayer:
    modules:
      - KnowledgeStore
      - MemoryRecallNode
      - MemoryStoreNode
  LearningLoop:
    modules:
      - ActiveLearningNode
      - ModelFineTuner
  QualityAssurance:
    modules:
      - EvaluatorNode
      - FeedbackCollectorNode
  FallbackEscalade:
    modules:
      - FallbackNodeAdvanced
      - EscalationManager
  Monitoring:
    modules:
      - MetricsCollector
      - AuditLogger
      - Tracing
  ProcessManagement:
    modules:
      - ProcessManager
      - MCP
  Resilience:
    modules:
      - RetryNode
      - CircuitBreakerNode
      - RateLimiterNode
  ToolIntegration:
    modules:
      - ToolAdapterNode
      - PluginRegistry
      - ToolRouterNode
  ToolLayer:
    modules:
      - Tool
      - PythonFunctionTool
      - PythonCodeTool
      - ChainedTool
      - ToolRegistry
      - ToolExecutor
      - ToolExecuteNode
      - ToolChainNode
  StateLayer:
    modules:
      - State
      - StateTransition
      - Checkpoint
      - StateMachine
      - StateManager
      - CheckpointManager
      - StateBackend
      - InMemoryBackend
      - FileBackend
      - PickleBackend
      - StateTransitionNode
      - CheckpointNode
  SecurityLayer:
    modules:
      - Authenticator
      - TokenAuthenticator
      - APIKeyAuthenticator
      - Sanitizer
      - RegexSanitizer
      - HTMLSanitizer
      - SecretsProvider
      - EnvironmentSecretsProvider
      - FileSecretsProvider
      - AuditLogger
      - RateLimiter
      - SecurityManager
      - AuthenticationNode
      - SanitizationNode
      - AuditNode
